/*
 * AboutJava1234InterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.zzsoft.company.view;

/**
 *
 * @author  __USER__
 */
public class AboutJava1234InterFrm extends javax.swing.JInternalFrame {

	/** Creates new form AboutJava1234InterFrm */
	public AboutJava1234InterFrm() {
		initComponents();
		this.setLocation(200, 50);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();

		setTitle("\u5173\u4e8eJava1234");

		jLabel1.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\caofeng\\Desktop\\images\\java1234.png")); // NOI18N

		jLabel2.setFont(new java.awt.Font("����", 2, 24));
		jLabel2.setForeground(new java.awt.Color(255, 51, 102));
		jLabel2
				.setText("\u5206\u4eab\u77e5\u8bc6\uff0c\u5206\u4eab\u5feb\u4e50");

		jLabel3.setFont(new java.awt.Font("΢���ź�", 2, 18));
		jLabel3
				.setText("www.java1234.com\u5b98\u7f51  \u6bcf\u65e5\u7b7e\u5230\uff0c\u6bcf\u65e5\u9001\u51fa10Q\u5e01");

		jLabel4.setFont(new java.awt.Font("΢���ź�", 0, 18));
		jLabel4
				.setText("\u62db\u6536Java\u95e8\u5f92\uff0cJava Web\u65b9\u5411\uff0c\u5168\u7a0b\u6307\u5bfc\uff0c\u9700\u8981\u5c11\u8bb8\u8d39\u7528");

		jLabel5.setFont(new java.awt.Font("΢���ź�", 0, 18));
		jLabel5
				.setText("\u6709\u610f\u5411\u8005\uff0c\u8054\u7cfbQQ\uff1a527085608");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup().addGap(25, 25,
										25).addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										225,
										javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(26, 26, 26).addComponent(
												jLabel2).addContainerGap(46,
												Short.MAX_VALUE))
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(37, 37, 37)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel5)
														.addComponent(
																jLabel4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																480,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																447,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(21, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel2).addComponent(jLabel1))
						.addGap(28, 28, 28).addComponent(jLabel3).addGap(30,
								30, 30).addComponent(jLabel4)
						.addGap(32, 32, 32).addComponent(jLabel5)
						.addContainerGap(92, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	// End of variables declaration//GEN-END:variables

}